# Generated by Django 4.1.7 on 2023-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyservice',
            name='Photo',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
