# Generated by Django 4.1.7 on 2023-05-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_beautyservice_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('Text', models.TextField()),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.beautyservice')),
            ],
        ),
        migrations.AddField(
            model_name='beautyservice',
            name='Group',
            field=models.ForeignKey( on_delete=django.db.models.deletion.PROTECT, to='catalog.beautyservicegroup', null=True, blank=True),
            preserve_default=False,
        ),
    ]
