# Generated by Django 4.1.7 on 2023-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_feedback_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackDate',
            field=models.DateTimeField(),
        ),
    ]
